name: Deploy Vite site (react-redraft) to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'react-redraft/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18          # keep what you've been using
          cache: npm
          cache-dependency-path: react-redraft/package-lock.json

      # Install with fallback (handles missing/old lockfiles)
      - name: Install deps
        run: |
          cd react-redraft
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Build (Vite)
        run: |
          cd react-redraft
          npm run build

      # Serve dist under /react-redraft/
      - name: Prepare artifact
        run: |
          rm -rf out
          mkdir -p out/react-redraft
          cp -r react-redraft/dist/. out/react-redraft/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
