name: Monthly Image Sender
on:
  schedule:
    # Runs at 9:00 AM UTC on the 1st of every month
    - cron: '0 9 1 * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome and Chrome Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pyyaml

      - name: Create config file
        env:
          EMAIL_LIST: ${{ secrets.EMAIL_LIST }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: |
          echo "email_list: ${EMAIL_LIST}" > config.yaml
          echo "smtp_server: ${SMTP_SERVER}" >> config.yaml
          echo "smtp_port: ${SMTP_PORT}" >> config.yaml
          echo "sender_email: ${SENDER_EMAIL}" >> config.yaml
          echo "sender_password: ${SENDER_PASSWORD}" >> config.yaml

      - name: Run image sender
        run: python scripts/monthly_image_sender.py
