name: Monthly Image Sender
on:
  schedule:
    # Runs at 9:00 AM UTC on the 1st of every month
    - cron: '0 9 1 * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f3 | cut -d '.' -f1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          curl -L -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pyyaml

      - name: Create config file
        env:
          EMAIL_LIST: ${{ secrets.EMAIL_LIST }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          SA_CREDENTIALS: ${{ secrets.SA_CREDENTIALS }}
        run: |
          echo "email_list: ${EMAIL_LIST}" > config.yaml
          echo "smtp_server: ${SMTP_SERVER}" >> config.yaml
          echo "smtp_port: ${SMTP_PORT}" >> config.yaml
          echo "sender_email: ${SENDER_EMAIL}" >> config.yaml
          echo "sender_password: ${SENDER_PASSWORD}" >> config.yaml
          echo "${SA_CREDENTIALS}" > service-account-credentials.json

      - name: Run image sender
        run: python scripts/infinite_bp/monthly_image_sender.py
