name: Manual Upload to Drive Folder
on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  upload-images:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 131
          install-chromedriver: true
          install-dependencies: true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pyyaml google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Create config file
        env:
          EMAIL_LIST: ${{ secrets.EMAIL_LIST }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          SA_CREDENTIALS: ${{ secrets.SA_CREDENTIALS }}
          LEAGUE_ID_LIST: ${{ secrets.LEAGUE_ID_LIST }}
          TEAM_ID_LIST: ${{ secrets.TEAM_ID_LIST }}
        run: |
          echo "email_list: ${EMAIL_LIST}" > config.yaml
          echo "smtp_server: ${SMTP_SERVER}" >> config.yaml
          echo "smtp_port: ${SMTP_PORT}" >> config.yaml
          echo "sender_email: ${SENDER_EMAIL}" >> config.yaml
          echo "sender_password: ${SENDER_PASSWORD}" >> config.yaml
          echo "league_id_list: ${LEAGUE_ID_LIST}" >> config.yaml
          echo "team_id_list: ${TEAM_ID_LIST}" >> config.yaml
          echo "${SA_CREDENTIALS}" > service-account-credentials.json

      - name: Run image sender
        run: python scripts/infinite_bp/monthly_image_sender.py -s=0
