name: release
on: [push]
permissions:
  contents: write
jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - run: git config user.name "${GITHUB_ACTOR}"
      - run: git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm run deploy
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
